repos:
- repo: git://github.com/pre-commit/pre-commit-hooks
  sha: v0.9.4
  hooks:
    - id: trailing-whitespace
- repo: git://github.com/pre-commit/mirrors-jshint
  sha: v2.9.5
  hooks:
    - id: jshint
      exclude: ^(src\/js\/lz-string.js|configs\/)
- repo: git://github.com/pre-commit/mirrors-fixmyjs
  sha: v2.0.0
  hooks:
    - id: fixmyjs
      args: ['-l', '-c', '.jshintrc']
      exclude: ^(src\/js\/lz-string.js|configs\/)
- repo: git://github.com/pre-commit/mirrors-eslint
  sha: v4.1.1
  hooks:
  - id: eslint
    additional_dependencies: [
      'eslint',
      'babel-eslint',
      'eslint-plugin-babel',
      'eslint-plugin-react',
      'eslint-plugin-promise',
      'eslint-plugin-prefer-object-spread',
      'eslint-plugin-no-loops',
      'eslint-plugin-sort-imports-es6-autofix'
    ]
    args: [--quiet]
    files: ^configs\/
    types: [javascript]
    exclude: (configs\/app\/js\/util\/lz-string.js|configs\/standalone-config\/generated.js|src\/js\/settings\/generated.js|configs\/server\/)
- repo: git://github.com/lfhbento/mirrors-prettier-eslint-cli
  sha: v4.1.1
  hooks:
  - id: prettier-eslint
    files: ^configs\/
    types: [javascript]
    exclude: (configs\/app\/js\/util\/lz-string.js|configs\/standalone-config\/generated.js|src\/js\/settings\/generated.js|configs\/server\/)
